# Generated by Django 4.2 on 2023-09-19 02:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meter_number",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                10000, "El número debe ser mayor o igual a 10000."
                            ),
                            django.core.validators.MaxValueValidator(
                                99999, "El número debe ser menor o igual a 99999."
                            ),
                        ]
                    ),
                ),
                ("user_name", models.CharField(max_length=20)),
                ("home_direction", models.CharField(max_length=20)),
                ("contract_type", models.CharField(max_length=20)),
                ("register_date", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
