# Generated by Django 4.2 on 2023-09-21 03:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Debts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meter_number",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                10000, "El número debe ser mayor o igual a 10000."
                            ),
                            django.core.validators.MaxValueValidator(
                                99999, "El número debe ser menor o igual a 99999."
                            ),
                        ]
                    ),
                ),
                ("ticket_year", models.PositiveSmallIntegerField()),
                ("ticket_month", models.PositiveSmallIntegerField()),
                ("ticket_cut", models.PositiveSmallIntegerField()),
                ("water_usage", models.DecimalField(decimal_places=4, max_digits=4)),
            ],
        ),
        migrations.DeleteModel(
            name="Debt",
        ),
        migrations.RemoveField(
            model_name="concepts",
            name="firefighters2",
        ),
        migrations.AlterField(
            model_name="users",
            name="contract_type",
            field=models.CharField(
                choices=[("R", "Residencial"), ("C", "Comercial"), ("I", "Industrial")],
                max_length=1,
            ),
        ),
    ]
