# Generated by Django 4.2 on 2023-09-21 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_debts_delete_debt_remove_concepts_firefighters2_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="debts",
            name="water_usage",
        ),
        migrations.AddField(
            model_name="debts",
            name="water_usage_m3",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
