# Generated by Django 4.2 on 2023-09-21 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_remove_debts_water_usage_debts_water_usage_m3"),
    ]

    operations = [
        migrations.RenameField(
            model_name="debts",
            old_name="ticket_cut",
            new_name="cut",
        ),
        migrations.RenameField(
            model_name="debts",
            old_name="ticket_month",
            new_name="month",
        ),
        migrations.RenameField(
            model_name="debts",
            old_name="ticket_year",
            new_name="year",
        ),
    ]
