# Generated by Django 4.2 on 2023-09-21 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_rename_ticket_cut_debts_cut_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="debts",
            name="debt",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
