# Generated by Django 4.2 on 2023-09-23 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0006_debts_previous_debt_debts_total_month"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="contract_type",
            field=models.CharField(
                choices=[
                    ("Residencial", "RESIDENCIAL"),
                    ("Comercial", "COMERCIAL"),
                    ("Industrial", "INDUSTRIAL"),
                ],
                max_length=12,
            ),
        ),
    ]
