# Generated by Django 4.2 on 2023-09-23 01:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0007_alter_users_contract_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="meter_number",
            field=models.IntegerField(
                unique=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        10000, "El número debe ser mayor o igual a 10000."
                    ),
                    django.core.validators.MaxValueValidator(
                        99999, "El número debe ser menor o igual a 99999."
                    ),
                ],
            ),
        ),
    ]
