# Generated by Django 4.2 on 2023-09-23 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0008_alter_users_meter_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="debts",
            name="debt",
        ),
        migrations.AlterField(
            model_name="concepts",
            name="consumption_per_cubic",
            field=models.FloatField(),
        ),
    ]
