# Generated by Django 4.2 on 2023-09-23 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0009_remove_debts_debt_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concepts",
            name="drainage_fee",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="concepts",
            name="firefighters",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="concepts",
            name="red_cross",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="concepts",
            name="sanitation",
            field=models.FloatField(),
        ),
    ]
