# Generated by Django 4.2 on 2023-09-24 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0010_alter_concepts_drainage_fee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="debts",
            name="contract_type",
            field=models.CharField(
                choices=[
                    ("Residencial", "RESIDENCIAL"),
                    ("Comercial", "COMERCIAL"),
                    ("Industrial", "INDUSTRIAL"),
                ],
                default="Residencial",
                max_length=12,
            ),
            preserve_default=False,
        ),
    ]
